2018-04-09 16:04:21.759 [error] <0.1600.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.1605.0> exit with reason normal in context child_terminated
2018-04-09 16:04:21.802 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:04:21.810 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:04:21.816 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:04:21.829 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-04-09 16:04:21.834 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:04:21.838 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:04:21.838 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:04:21.847 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:04:21.847 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:04:21.853 [error] <0.1661.0>@Elixir.GenServer:call CRASH REPORT Process <0.1661.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.1661.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in 'Elixir.GenServer':call/3 line 824
2018-04-09 16:04:21.854 [error] <0.1660.0>@Elixir.GenServer:call Supervisor 'Elixir.Consumer.Supervisor' had child 'Elixir.Consumer.Repo' started with 'Elixir.Consumer.Repo':start_link() at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.1661.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in context start_error
2018-04-09 16:04:21.854 [error] <0.1658.0> CRASH REPORT Process <0.1658.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.1661.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...} in application_master:init/4 line 134
2018-04-09 16:05:15.994 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-04-09 16:05:16.030 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:05:16.040 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:05:16.045 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:05:16.055 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-04-09 16:05:16.058 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:05:16.061 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:05:16.061 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:05:16.069 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:05:16.069 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:05:16.078 [error] <0.252.0>@Elixir.GenServer:call CRASH REPORT Process <0.252.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in 'Elixir.GenServer':call/3 line 824
2018-04-09 16:05:16.078 [error] <0.251.0>@Elixir.GenServer:call Supervisor 'Elixir.Consumer.Supervisor' had child 'Elixir.Consumer.Repo' started with 'Elixir.Consumer.Repo':start_link() at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in context start_error
2018-04-09 16:05:16.078 [error] <0.249.0> CRASH REPORT Process <0.249.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...} in application_master:init/4 line 134
2018-04-09 16:05:16.141 [info] <0.33.0> Application consumer exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...}
2018-04-09 16:05:34.319 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
2018-04-09 16:05:34.358 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:05:34.368 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:05:34.374 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:05:34.383 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-04-09 16:05:34.387 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:05:34.391 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:05:34.391 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:05:34.399 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:05:34.399 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:05:34.408 [error] <0.261.0>@Elixir.GenServer:call CRASH REPORT Process <0.261.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.261.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in 'Elixir.GenServer':call/3 line 824
2018-04-09 16:05:34.408 [error] <0.260.0>@Elixir.GenServer:call Supervisor 'Elixir.Consumer.Supervisor' had child 'Elixir.Consumer.Repo' started with 'Elixir.Consumer.Repo':start_link() at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.261.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in context start_error
2018-04-09 16:05:34.408 [error] <0.258.0> CRASH REPORT Process <0.258.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.261.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...} in application_master:init/4 line 134
2018-04-09 16:05:34.468 [info] <0.33.0> Application consumer exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.261.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...}
2018-04-09 16:06:59.832 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-04-09 16:06:59.881 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:06:59.890 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:06:59.895 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:06:59.907 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-04-09 16:06:59.911 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:06:59.914 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:06:59.914 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:06:59.921 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:06:59.921 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:06:59.929 [error] <0.252.0>@Elixir.GenServer:call CRASH REPORT Process <0.252.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in 'Elixir.GenServer':call/3 line 824
2018-04-09 16:06:59.929 [error] <0.251.0>@Elixir.GenServer:call Supervisor 'Elixir.Consumer.Supervisor' had child 'Elixir.Consumer.Repo' started with 'Elixir.Consumer.Repo':start_link() at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in context start_error
2018-04-09 16:06:59.929 [error] <0.249.0> CRASH REPORT Process <0.249.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...} in application_master:init/4 line 134
2018-04-09 16:07:00.011 [info] <0.33.0> Application consumer exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.252.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...}
2018-04-09 16:12:05.802 [error] <0.594.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.599.0> exit with reason normal in context child_terminated
2018-04-09 16:12:05.837 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:12:05.844 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:12:05.849 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:12:05.862 [info] <0.33.0> Application ranch started on node nonode@nohost
2018-04-09 16:12:05.866 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:12:05.869 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:12:05.870 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:12:05.878 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:12:05.878 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:12:05.882 [error] <0.655.0>@Elixir.GenServer:call CRASH REPORT Process <0.655.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.655.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in 'Elixir.GenServer':call/3 line 824
2018-04-09 16:12:05.882 [error] <0.654.0>@Elixir.GenServer:call Supervisor 'Elixir.Consumer.Supervisor' had child 'Elixir.Consumer.Repo' started with 'Elixir.Consumer.Repo':start_link() at undefined exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Ecto.Registry', {associate,<0.655.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},...]}}, 5000) in context start_error
2018-04-09 16:12:05.883 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Consumer.Repo',{noproc,{'Elixir.GenServer',call,['Elixir.Ecto.Registry',{associate,<0.655.0>,{'Elixir.Consumer.Repo','Elixir.Consumer.Repo.Pool',[{name,'Elixir.Consumer.Repo.Pool'},{otp_app,consumer},{repo,'Elixir.Consumer.Repo'},{timeout,15000},{pool_timeout,5000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{username,<<"postgres">>},{password,<<"postgres">>},{database,<<"consumer_dev">>},{hostname,<<"localhost">>},{pool_size,10},{pool,'Elixir.DBConnection.Poolboy'}]}},...]}}}},...} in application_master:init/4 line 134
2018-04-09 16:12:33.275 [error] <0.313.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.318.0> exit with reason normal in context child_terminated
2018-04-09 16:12:33.313 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:12:33.323 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:12:33.329 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:12:33.334 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:12:33.339 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:12:33.339 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:12:33.349 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:12:33.349 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:12:33.361 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:12:33.380 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:12:33.386 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:12:33.393 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:12:33.401 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:12:33.406 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:12:33.409 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:12:34.275 [warning] <0.32.0> lager_error_logger_h dropped 85 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:17:20.645 [error] <0.313.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.318.0> exit with reason normal in context child_terminated
2018-04-09 16:17:20.687 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:17:20.697 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:17:20.705 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:17:20.710 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:17:20.714 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:17:20.715 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:17:20.725 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:17:20.725 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:17:20.738 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:17:20.754 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:17:20.759 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:17:20.764 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:17:20.772 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:17:20.776 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:17:20.779 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:17:21.005 [warning] <0.32.0> lager_error_logger_h dropped 95 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:17:21.005 [info] <0.33.0> Application consumer started on node nonode@nohost
2018-04-09 16:17:44.852 [error] <0.449.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.454.0> exit with reason normal in context child_terminated
2018-04-09 16:17:44.889 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:17:44.899 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:17:44.907 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:17:44.912 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:17:44.917 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:17:44.917 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:17:44.926 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:17:44.926 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:17:44.939 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:17:44.955 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:17:44.960 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:17:44.967 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:17:44.974 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:17:44.978 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:17:44.981 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:17:46.001 [warning] <0.32.0> lager_error_logger_h dropped 46 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:26:08.694 [error] <0.732.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:12.221 [error] <0.740.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:16.327 [error] <0.745.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:22.570 [error] <0.747.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:33.196 [error] <0.749.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:44.512 [error] <0.751.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:26:55.260 [error] <0.753.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:27:06.561 [error] <0.755.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:27:17.134 [error] <0.757.0> Ranch listener 'Elixir.ConsumerWeb.Endpoint.HTTP' terminated with reason: {{undef,[{'Elixir.ConsumerWeb.RoomChannel','__socket__',[private],[]},{'Elixir.Phoenix.Socket.Transport',build_channel_socket,5,[{file,"lib/phoenix/socket/transport.ex"},{line,261}]},{'Elixir.Phoenix.Socket.Transport',do_dispatch,3,[{file,"lib/phoenix/socket/transport.ex"},{line,267}]},{'Elixir.Phoenix.Transports.WebSocket',ws_handle,3,[{file,"lib/phoenix/transports/websocket.ex"},{line,123}]},{'Elixir.Phoenix.Endpoint.CowboyWebSocket',websocket_handle,3,[{file,"lib/phoenix/endpoint/cowboy..."},...]},...]},...}
2018-04-09 16:46:12.714 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2018-04-09 16:46:12.742 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:46:12.751 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:46:12.757 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:46:12.762 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:46:12.766 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:46:12.766 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:46:12.773 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:46:12.773 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:46:12.785 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:46:12.799 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:46:12.804 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:46:12.809 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:46:12.815 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:46:12.818 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:46:12.820 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:46:13.002 [warning] <0.32.0> lager_error_logger_h dropped 84 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:46:13.066 [info] <0.33.0> Application consumer started on node nonode@nohost
2018-04-09 16:47:11.481 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
2018-04-09 16:47:11.510 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:47:11.520 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:47:11.526 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:47:11.530 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:47:11.534 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:47:11.534 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:47:11.541 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:47:11.541 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:47:11.552 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:47:11.565 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:47:11.569 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:47:11.574 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:47:11.580 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:47:11.584 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:47:11.587 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:47:12.260 [warning] <0.32.0> lager_error_logger_h dropped 75 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:49:25.605 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.197.0> exit with reason normal in context child_terminated
2018-04-09 16:49:25.636 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:49:25.643 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:49:25.648 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:49:25.651 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:49:25.655 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:49:25.655 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:49:25.661 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:49:25.661 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:49:25.671 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:49:25.682 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:49:25.686 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:49:25.690 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:49:25.696 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:49:25.699 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:49:25.701 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:49:26.234 [warning] <0.32.0> lager_error_logger_h dropped 94 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:51:38.916 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.197.0> exit with reason normal in context child_terminated
2018-04-09 16:51:38.947 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:51:38.957 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:51:38.963 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:51:38.968 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:51:38.973 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:51:38.973 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:51:38.980 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:51:38.981 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:51:38.990 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:51:39.003 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:51:39.008 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:51:39.012 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:51:39.020 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:51:39.023 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:51:39.025 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:51:40.001 [warning] <0.32.0> lager_error_logger_h dropped 45 messages in the last second that exceeded the limit of 50 messages/sec
2018-04-09 16:53:26.351 [error] <0.200.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.205.0> exit with reason normal in context child_terminated
2018-04-09 16:53:26.390 [info] <0.33.0> Application lager started on node nonode@nohost
2018-04-09 16:53:26.399 [info] <0.33.0> Application xmerl started on node nonode@nohost
2018-04-09 16:53:26.405 [info] <0.33.0> Application jsx started on node nonode@nohost
2018-04-09 16:53:26.409 [info] <0.33.0> Application ranch_proxy_protocol started on node nonode@nohost
2018-04-09 16:53:26.413 [info] <0.33.0> Application recon started on node nonode@nohost
2018-04-09 16:53:26.413 [info] <0.33.0> Application rabbit_common started on node nonode@nohost
2018-04-09 16:53:26.421 [info] <0.33.0> Application amqp_client started on node nonode@nohost
2018-04-09 16:53:26.421 [info] <0.33.0> Application amqp started on node nonode@nohost
2018-04-09 16:53:26.431 [info] <0.33.0> Application connection started on node nonode@nohost
2018-04-09 16:53:26.443 [info] <0.33.0> Application db_connection started on node nonode@nohost
2018-04-09 16:53:26.447 [info] <0.33.0> Application decimal started on node nonode@nohost
2018-04-09 16:53:26.451 [info] <0.33.0> Application postgrex started on node nonode@nohost
2018-04-09 16:53:26.457 [info] <0.33.0> Application poolboy started on node nonode@nohost
2018-04-09 16:53:26.460 [info] <0.33.0> Application ecto started on node nonode@nohost
2018-04-09 16:53:26.462 [info] <0.33.0> Application phoenix_ecto started on node nonode@nohost
2018-04-09 16:53:27.263 [warning] <0.32.0> lager_error_logger_h dropped 50 messages in the last second that exceeded the limit of 50 messages/sec
